
#config server
spring.application.name=CATALOG-SERVICE
spring.config.import=optional:configserver:http://localhost:8888

# Internal service-to-service authentication token
service.token.secret=ShopSphere-Internal-Secret-2026
